

export const menuItems=[
    {
        title:"Dashboard",
        path:"/dashboard",
    },
    {
        title:"AddBook",
        path:"/addbook",  
    },
    {
        title:"UserList",
        path:"/userlist",  
    },
    {
        title:"AddUser",
        path:"/adduser",  
    },
    {
        title:"BorrowedBook",
        path:"/borrowbook",  
    },
    {
        title:"ReturnBook",
        path:"/returnbook",  
    },
    {
        title:"Analytics",
        path:"/analytics",  
    },
    {
        title:"Chart",
        path:"/chart",  
    },
    {
        title:"Logout",
        path:"/logout",  
    }
]