"""remade return table

Revision ID: 08c9af8c49ee
Revises: 490413f86ed8
Create Date: 2025-05-17 10:34:37.764605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c9af8c49ee'
down_revision = '490413f86ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('returned_books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returned_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('borrowed_book_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['borrowed_book_id'], ['borrowed_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('return_books')
    # ### end Alembic commands ###
