"""Add ReturnBook table

Revision ID: 490413f86ed8
Revises: 6c7e1cdb1fff
Create Date: 2025-05-17 00:44:36.062711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490413f86ed8'
down_revision = '6c7e1cdb1fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returned_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrowed_book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['borrowed_book_id'], ['borrowed_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('returned_books')
    # ### end Alembic commands ###
