"""updated borrowedbook

Revision ID: 6c3641bf7e33
Revises: 6ca9531defe8
Create Date: 2025-05-16 02:47:57.806740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3641bf7e33'
down_revision = '6ca9531defe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.drop_column('borrowed_at')
        batch_op.drop_column('due_date')
        batch_op.drop_column('returned_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('borrowed_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
