"""Add role column to user

Revision ID: 78097f99f0c3
Revises: 08c9af8c49ee
Create Date: 2025-05-18 00:21:40.426195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78097f99f0c3'
down_revision = '08c9af8c49ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
